RobotError: Use __str__ for formatting the error.
On a traceback, the __str__ value will be read instead of __repr__ so we
get the name of the exception class, but not the actual exception.

This is now no longer the case :-)

Signed-off-by: aszlig <aszlig@redmoonstudios.org>