server: Improve error handling for admin accounts
Instead of the assertion we had before, let's throw a WebRobotError
encoding exactly what has failed. This should give a more helpful error
message.

For example now if server.admin.create('xxxxxxxx') is used:

hetzner.WebRobotError: Unable to create admin account:
    Mindestens ein Gro?buchstabe, Mindestens eine Zahl oder ein
    Sonderzeichen

Signed-off-by: aszlig <aszlig@redmoonstudios.org>
(cherry picked from commit ca2d1311abbf4ab11dac8fa8dbf1e3895b65aa72)