RobotError: Don't call __init__() supermethod
First of all, the change introduced in
330ce550f4d31a7a43625537e414e4e9794a8043 is not PEP8-compliant (too long
line) and also I think it's a bit odd to call the __init__() method of
Exception *without* giving it a status attribute and then setting it in
our own __init__().

Setting self.message and self.status directly is also documented in the
official Python documentation, so we don't rely on internals here as
well, see:

https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions

Signed-off-by: aszlig <aszlig@redmoonstudios.org>