RobotError: Assign status to the instance
Regression introduced by c7181fd0763a08754a3305da82e1bb649827f4a1.

The mentioned commit accidentally removed the status attribute, which we
currently need to check for the HTTP status code in some requests.

Signed-off-by: aszlig <aszlig@nix.build>