robot: Enhance and fix error printing.
This will now show something like:

hetzner.robot.RobotError: 400 - invalid input, fields: server_name

Instead of being way more error-prone and printing something like this,
where we have the error message actually printed twice:

hetzner.robot.RobotError: 400 - invalid input, invalid input: server_name

Signed-off-by: aszlig <aszlig@redmoonstudios.org>